### PR TITLE
Allow to change if midi type on reset instead of needing a core restart

### PR DESCRIPTION
**Pull request by negativeExponent**
This is safe to do.

### CODE REVIEW

**Comment by Kelvfimer** [comment]
Pls @kivutar can you review the PRs made by @negativeExponent he has been evolving the core https://github.com/negativeExponent/px68k-libretro and he will be adding more PRs for new capabilities to it to enhance its performance features thx so much.

**Comment by negativeExponent** [comment]
you may want to tag LibretroAdmin instead as he is the one who merges most of the things if not all of them.

**Comment by negativeExponent** [comment]
> you may want to tag LibretroAdmin instead as he is the one who merges most of the things if not all of them.

@LibretroAdmin

**Comment by negativeExponent** [comment]
deprecated by this PR https://github.com/libretro/px68k-libretro/pull/177

**Comment by negativeExponent** [comment]
this should be safe to merge now @LibretroAdmin

**Comment by LibretroAdmin** [comment]
Alright, thanks.

**Pull request merged**
