### PR TITLE
Restore MIDI output core options

### LINKED ISSUE #166: "px68k_midi_output" and "px68k_midi_output_type" invalid value errors
Getting this in logs every time the core boots:

> [ERROR] [Environ]: GET_VARIABLE: px68k_midi_output - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: px68k_midi_output_type - Invalid value.

This is because this function still exists: https://github.com/libretro/px68k-libretro/blob/4c7542e34df71e3ebab77b5867901747d58dbb38/libretro.c#L320-L349

while the core options were removed in commit 9ac92513a16c90df3ef2eed39572a24fbc4d75f2

I wanted to make a PR, but idk if I was supposed to remove the function or re-add the 2 core options (I have no idea if they work, I never messed with the MIDI stuff) :p So I prefer to open an issue about it instead.

### PR DESCRIPTION
**Pull request by bslenul**
Closes #166

### CODE REVIEW

**Comment by Kelvfimer** [comment]
@bslenul if "px68k_midi_output", is set to off at least Castlevania is not starting. 

I would like to check what is the right setting. I was using these settings px68k_midi = "enabled" and px68k_midi_type = "LA" instead of the output ones you used.

**Comment by Kelvfimer** [comment]
Strange those values px68k_midi = "enabled" and px68k_midi_type = "LA" doesn't exist in the code but I took them from here and they are working https://retropie.org.uk/forum/topic/33298/playing-x68000-games-with-midi-music

**Comment by gingerbeardman** [comment]
It's here in the code. INI settings are converted into a structure that is used in the code.

https://github.com/libretro/px68k-libretro/blob/4c7542e34df71e3ebab77b5867901747d58dbb38/libretro.c#L320-L349

**Comment by Kelvfimer** [comment]
@gingerbeardman the values of the page for sure are not the right ones. 

@gingerbeardman  can you merge this PR? thx or it is @LibretroAdmin  the one who should do it? thx

**Pull request merged**
