### PR TITLE
(DO NOT MERGE YET) win32: direct midi support through winmm

### PR DESCRIPTION
**Pull request by negativeExponent**

### CODE REVIEW

**Comment by Kelvfimer** [comment]
Is this working for linux as well? @negativeExponent ? I saw you closed the other PR and I was interested in not resetting PX68 everytime I change the midi mode. thx

**Comment by negativeExponent** [comment]
Linux, by default will will use libretro for midi.  Previous PR are not necessary anymore coz they're already included here.

**Comment by negativeExponent** [comment]
this may not be needed anymore after this PR will be verified and merged: https://github.com/libretro/RetroArch/pull/16804

individual fixed i will re-send on different PR after that one as that bug has been an issue since

**Comment by LibretroAdmin** [comment]
So this PR can be closed now because the other ones got merged already?

**Comment by negativeExponent** [comment]
true. thanks

**Pull request closed without merging**
