### PR TITLE
Keyboard changes, Japanese encoding test, Menu Joypad Button

### PR DESCRIPTION
**Pull request by Tatsuya79**
Changed some keys as I was lacking ";" on my keyboard.
I couldn't use the shift+break combo too before (self destruct in Aquales to go back to menu, exit of some Human68k menu...).
Used F11 for "Help". Not sure if that can cause a problem with that debugger mode?
It could be moved to print screen if that's the case as "symbol input" doesn't seem to be really needed (XM6 Type G isn't mapping it by default).

I tried to make the Japanese characters works.
I went to the upstream repo, displayed a raw page, had to force EUC encoding in firefox to display fine.
Copied that to the same file I had to force UTF-8 in notepad++, send that to Github.

Now Github displays everything fine on every page!? It needed 1 file in UTF-8 or something?
Still come back as ANSI when cloning locally... ugh.
Whatever.

Added a Menu call on Joypad L2, thanks to @retro-wertz.

### CODE REVIEW

**Comment by r-type** [comment]
could you just keep the order in keyboard fixes
like 
KEYP(RETROK_EQUALS,0xe); //Yen symbol ¥ (equals is on shift+minus)
after KEYP(RETROK_RETURN,0x1d);

KEYP(RETROK_F11,0x54); //help
after KEYP(RETROK_SCROLLOCK,0x53); //registration (touroku)
ect...

**Comment by Tatsuya79** [comment]
Ok, hope that's just those ones?
It's a bit misleading between x68k/azerty/qwerty and different keyboard models sometimes...

**Comment by r-type** [comment]
to be honest you  miss
KEYP(RETROK_BACKSLASH,0x28); // colon :
else all seem ok

**Comment by Tatsuya79** [comment]
OK, I think I was trying to follow the qwerty keyboard at some point...

**Pull request merged**
