### PR TITLE
Automatically switch refresh rates depending on game

### PR DESCRIPTION
**Pull request by retro-wertz**
Most games use 55.45 fps, but others will use 61.46 . This should allow automatic-switch of fps depending on game.
Instead of using 61.46 for ->timing.fps, 59.94 is used to reduce audio stutters and other possible audio-related issues since most monitors run only at 60Hz.

### CODE REVIEW

**Comment by r-type** [comment]
Update geometry is used to switch things like résolution.
It not suitable to update fps.
You have to use retro_get_system_av_info(struct retro_system_av_info *info)
To switch things like fps.
You should look at how we deal this in mame source code (in osd libretro internal)
Updt geometry only if resolution change reesolution change
And system av info for things like fps

**Comment by r-type** [comment]
That said im not sure that always the case. Maybe @twinaphex can confirm or say if it is not the case

**Comment by retro-wertz** [comment]
"You have to use retro_get_system_av_info(struct retro_system_av_info
*info)"

its there,
https://github.com/libretro/px68k-libretro/pull/11/commits/25b63c548407d18c1aa3f5b42ea82c8bd410e3ad#diff-52976fe74a1572089032df837f0630a3R376

**Comment by r-type** [comment]
ok i didn't notice it was in  update_geometry(void).
the bad thing then is that is done in update_geometry, so when we only change resolution (using CHANGEAV == 1 ) we also doing an retro_get_system_av_info (which is bad because can raise a driver reinitialization). we need to separe them like in mame code 
https://github.com/libretro/mame/blob/master/src/osd/libretro/libretro-internal/libretro.cpp

taken from libretro.h
 ***HIGHLY RECOMMENDED*** Do not call this callback every time 
                                            * resolution changes in an emulator core if it's
                                            * expected to be a temporary change, for the reasons of possible 
                                            * driver reinitialization.
                                            * This call is not a free pass for not trying to provide 
                                            * correct values in retro_get_system_av_info(). If you need to change 
                                            * things like aspect ratio or nominal width/height, 
                                            * use RETRO_ENVIRONMENT_SET_GEOMETRY, which is a softer variant 
                                            * of SET_SYSTEM_AV_INFO.
                                            *

**Comment by r-type** [comment]
best is to done things like if fps change then CHANGEAV=2 , if only res CHANGEAV=1
and deal like 

if (CHANGEAV == 1)
   {
      struct retro_system_av_info ninfo;

      retro_get_system_av_info(&ninfo);

      environ_cb(RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO, &ninfo);
...
   }
   else if (CHANGEAV == 2){
      update_geometry();
     ...
   }
like in mame code.

**Comment by retro-wertz** [comment]
driver init only happens(from my tests at least) when you use
RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO. as far as updating fps,
RETRO_ENVIRONMENT_SET_GEOMETRY does the the job, unless this is a bug. this
is how i added region switch for fceumm to change to NTSC, PAL or DENDY.

i can re-implement the refresh update part as separate fuctions, but its
still be using RETRO_ENVIRONMENT_SET_GEOMETRY as changing fps is not
necessary to reinitialize the core. only when changing soundrate that you
need to use RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO.

but i get the point. ill just pull out retro_get_system_info from
update_geometry, and just redo it without writing to geometry pointer.

**Comment by r-type** [comment]
> but i get the point. ill just pull out retro_get_system_info from update_geometry, and just redo it without writing to geometry pointer.
yes that is the point : ) it will be fine to not mix  retro_get_system_info in update_geometry

Btw it's a nice addition to add ability to switch fps when needed !

**Comment by retro-wertz** [comment]
added new update
-update how change in fps is checked
-used separate "CHECKAV_TIMING" to avoid being overwritten when a change in resolution is detected but does not request a change in fps

**Comment by retro-wertz** [comment]
updated PR again, and just implement changing timings only and not using retro_get_system_av_info(), more likely this is a "timing" version of update_geometry(). this does send invalid SET_GEOMETRY info to debug window though, but it should work.

**Comment by retro-wertz** [comment]
simplify further update_timing, which only updates "av_info.timing.fps" to change fps.
@hunterk

**Pull request merged**
