### PR TITLE
add touroku map joy R2

### PR DESCRIPTION
**Pull request by Kelvfimer**

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
@negativeexponent What do you think about this PR? Is it fit for merge?

**Comment by negativeExponent** [comment]
@Kelvfimer can you add these to input descriptors so the label  visible from the input keymap?

`{ 0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_R2, "R2" },`

change to

`{ 0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_R2, "R2 - Touroku" },`

after thats added, this can be merged. its fine as-is but better to see the labels.

thanks.

**Comment by Kelvfimer** [comment]
@negativeExponent done :) THX!!

**Comment by negativeExponent** [comment]
@LibretroAdmin this is ok now to merge.

**Pull request merged**
