### PR TITLE
KeyBindings in a table array with comments, new key combinations for unmapped keys, analog controller support etc

### PR DESCRIPTION
**Pull request by negativeExponent**
Fix https://github.com/libretro/px68k-libretro/issues/142

@LibretroAdmin @hunterk @hizzlekizzle

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Wow, ton of great stuff in here. I'll see if we can get it merged ASAP.

I wasn't sure if this was actually an (unimportant) issue or just a missing font on my system or something:
image

**Comment by negativeExponent** [comment]
thanks for the reply. bah that txt do not mean anything relevant. i have a lot to port from my repo of px68k but its dragging to much waiting for things to get merged or evaluated. anyone else i can tag to evaluate at least to make things go faster?

**Comment by hizzlekizzle** [comment]
Hmm, not sure. I just now saw it and pinged libretroadmin on discord to make sure he sees it. I'm not sure who else, other than him, has merge rights to the repo (I don't, but I can usually get eyes on stuff).

**Comment by gingerbeardman** [comment]
> I wasn't sure if this was actually an (unimportant) issue or just a missing font on my system or something:

The Japanese text in the original file is Shift-JIS not Unicode, so some editors will clobber it. The correct way to keep it is to use a editor that will convert to Unicode or edit the files as Shift-JIS. On macOS I use Cot Editor, not sure about other platforms. 

I raised the issue of keeping a while ago but there were unanswered questions regarding compilation, and then the comments just started getting mangled. 

ps: the text refers to MAME-compatible register numbers.

**Comment by LibretroAdmin** [comment]
Sorry for the delay @negativeExponent. There will hopefully be less time until merge from now on.

**Pull request merged**
