### PR TITLE
Added PS3 build

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by negativeExponent** [comment]
i assume that this core does indeed work on PS3, so merging it.

**Comment by crystalct** [comment]
Unfortunatly, px68k needs some big endian fixes to work correctly on WIIU, PS3 and so on...

**Comment by negativeExponent** [comment]
oh pS3 is BE, its a nono then...

**Comment by crystalct** [comment]
Fix a big endian issue is easy.... the part complex and loooooong is to find them.

**Pull request merged**
