### PR TITLE
Don't save FDD and HDD paths to config file

### PR DESCRIPTION
**Pull request by Exalm**
Also, what's up with all the `#if 0`'d dead code? Should I just remove it instead? :)

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi, where do we stand with this PR?

**Comment by Exalm** [comment]
Well, I still not sure about the scenario #3. Are there any cores that do that? The current behavior is just completely unintuitive, as you load one game and another one loads for no reason

**Comment by gingerbeardman** [comment]
> you load one game and another one loads for no reason

@Exalm is this actually true? If so it's not covered by and of the above scenarios. 

Or are you referring to 3, when a user loads the core it loads the last game they were playing?

**Comment by Exalm** [comment]
Yes, it is true. Try this:

1. Load a game from a floppy
2. Close it
3. Load a game from an HDD. Oops, it still loads the game from that floppy

**Comment by gingerbeardman** [comment]
>Yes, it is true. Try this: ...

@Exalm the thing is, that's exactly what would happen with the real hardware. You would need to eject the floppy for it to not take booting order precedence over the hard drive. 

My uncommitted changes add an option for the user to choose whether or not they want this kind of realistic persistence. 

At this point, though, I really don't have strong opinion either say on this. Though I still believe that any changes to long-standing behaviour should come as a toggle option.

**Comment by negativeExponent** [comment]
this can now be closed. implemented as core options i latest commit

**Pull request closed without merging**
