### PR TITLE
MEM map and joypad updates

### PR DESCRIPTION
**Pull request by retro-wertz**

### CODE REVIEW

**Comment by retro-wertz** [comment]
close this too. i guess only hacks are allowed to get merged....

**Comment by gingerbeardman** [comment]
@retro-wertz what do you mean?

**Comment by retro-wertz** [comment]
you better ask them.. im not the one who is able to merge PR's

**Comment by gingerbeardman** [comment]
OK. I've a bunch of changes I want to PR soon

**Comment by retro-wertz** [comment]
ive heard that many times from you that you are going to push something since a few months ago, havent seen even one yet.
You should push some if you have them working already. besides, this issue is just against me. im clearing my stuff and walking away....

**Comment by fr500** [comment]
Hey @retro-wertz not sure what's up?
The snes9x situation? I think everything was rolled back and we kinda agreed to have a mostly vanilla port.

FWIW I agree hacks should be in forks or whatever and not really in mainline.

**Pull request closed without merging**
