### PR TITLE
Add save state handling

### PR DESCRIPTION
**Pull request by negativeExponent**
This is a 2nd push for the same PR to get rid of some forced-push commits

Some notes to consider:
- consider this wip. some vars might not be necessary.
- only for C68K cpu core
- minimally tested. it works on HD files, and multi-disks but have not tested on anything that switches to another disk yet or drive letter.
- M3U/CMD platlist format is necessary to keep track of what content the state is for (filename for .statex tracking for example). Switching disk or switching to another game through ingame menu will break currently loaded state.
- in core is use to run in content-less mode, the savestate will be universal or system state (PX68K.state) and will not be based on what content is loaded.
- MIDI: Loading patchsets and other midi params from a state file is not implemented. It may take a while to refresh instruments sets until next time MIDI sends new data. Its also required that only load a state after selecting the correct MIDI device from the ingame menu.
- requires new px68k_libretro.info file, with savestate support enabled

### CODE REVIEW

**Comment by negativeExponent** [comment]
@LibretroAdmin @hunterk @hizzlekizzle

nobody appears to be monitoring this repo. is this stil open for maintenance/updates? this is the 2nd push of the same PR that was sent 3 days ago or so.

**Comment by hizzlekizzle** [comment]
yeah, these PRs are not showing up in my feed. If you don't mind, just @ us so we see it.

**Comment by negativeExponent** [comment]
bah just pull stuff my my repo. cant keep doing this waiting when to get merge thing to happen. it hinders momentum in sending/doing next things to push for.

**Comment by LibretroAdmin** [comment]
Do you want write access to the repo? We'd be more than willing to provide it.

**Comment by LibretroAdmin** [comment]
I'm guessing that's a no then. I can assure you nobody is there purposefully ignoring your PRs, and you're always welcome on our Discord and I guarantee you all you'd need to do is just ping us and it'd immediately get merged.

**Comment by LibretroAdmin** [comment]
The offer still stands. I think all users are just helped if we all used the remainder of our time to work together and just work on teh same codebase. I can just give you write access and we more than trust your commits and you'd be able to just push it through.

**Comment by LibretroAdmin** [comment]
I'll send you an invitation anyway. Hope you reconsider, and if not, still appreciate your work.

**Pull request closed without merging**
